package com.crm.dao.mapper;

import me.gacl.domain.CUser;
import me.gacl.domain.CUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int countByExample(CUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int deleteByExample(CUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int insert(CUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int insertSelective(CUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	List<CUser> selectByExample(CUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	CUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CUser record,
                                 @Param("example") CUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int updateByExample(@Param("record") CUser record,
                        @Param("example") CUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int updateByPrimaryKeySelective(CUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_user
	 * @mbggenerated  Tue Aug 16 20:29:08 CST 2016
	 */
	int updateByPrimaryKey(CUser record);
}