package com.crm.dao.mapper;

import java.util.List;
import me.gacl.domain.Dessy;
import me.gacl.domain.DessyExample;
import org.apache.ibatis.annotations.Param;

public interface DessyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int countByExample(DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int deleteByExample(DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int insert(Dessy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int insertSelective(Dessy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    List<Dessy> selectByExample(DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    Dessy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") Dessy record, @Param("example") DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int updateByExample(@Param("record") Dessy record, @Param("example") DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int updateByPrimaryKeySelective(Dessy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    int updateByPrimaryKey(Dessy record);
}