package com.crm.dao.mapper;

import java.util.List;
import me.gacl.domain.ECoupon;
import me.gacl.domain.ECouponExample;
import org.apache.ibatis.annotations.Param;

public interface ECouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int countByExample(ECouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int deleteByExample(ECouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int insert(ECoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int insertSelective(ECoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    List<ECoupon> selectByExample(ECouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    ECoupon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") ECoupon record, @Param("example") ECouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int updateByExample(@Param("record") ECoupon record, @Param("example") ECouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int updateByPrimaryKeySelective(ECoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    int updateByPrimaryKey(ECoupon record);
}