package com.crm.dao.mapper;

import java.util.List;
import me.gacl.domain.Dessy;
import me.gacl.domain.DessyExample;
import org.apache.ibatis.annotations.Param;

public interface DessyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int countByExample(DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int deleteByExample(DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int insert(Dessy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int insertSelective(Dessy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    List<Dessy> selectByExample(DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    Dessy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") Dessy record, @Param("example") DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int updateByExample(@Param("record") Dessy record, @Param("example") DessyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int updateByPrimaryKeySelective(Dessy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dessy
     *
     * @mbggenerated Tue Aug 30 17:48:40 CST 2016
     */
    int updateByPrimaryKey(Dessy record);
}