package com.crm.dao.mapper;

import java.util.List;
import me.gacl.domain.Disscuss;
import me.gacl.domain.DisscussExample;
import org.apache.ibatis.annotations.Param;

public interface DisscussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int countByExample(DisscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int deleteByExample(DisscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int insert(Disscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int insertSelective(Disscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    List<Disscuss> selectByExample(DisscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    Disscuss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") Disscuss record, @Param("example") DisscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int updateByExample(@Param("record") Disscuss record, @Param("example") DisscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int updateByPrimaryKeySelective(Disscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    int updateByPrimaryKey(Disscuss record);
}