package me.gacl.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.*;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Created by jason_moo on 2017/12/21.
 */

@Document(indexName= CaseInfoES.INDEX, type= CaseInfoES.PARENT_TYPE, indexStoreType = "memory", shards = 3, replicas = 0, refreshInterval = "-1")
public class CaseInfoES {

    public static final String INDEX = "xkeshi_market_caseinfo";

    public static final String PARENT_TYPE = "case_info";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.coupon_info_code
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.text,index = false)
    private String couponInfoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.coupon_info_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.text)
    private String couponInfoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.coupon_category_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Integer)
    private Byte couponCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.is_available
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Integer)
    private Byte isAvailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.business_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.text)
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.shop_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Long)
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.merchant_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Long)
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.facture
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Integer)
    private Byte facture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.substitute_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Long)
    private Long substituteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.substitute_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.text)
    private String substituteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.sub_agent_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Long)
    private Long subAgentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.valid_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Date)
    private Date validTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.expire_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Date)
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.valid_days
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Integer)
    private Integer validDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.denomination
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Double)
    private BigDecimal denomination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.introduction
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.text)
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.detail_pic
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.text)
    private String detailPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.apply_all_shop
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Integer)
    private Byte applyAllShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.is_anytime
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Integer)
    private Byte isAnytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.binding_hours
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.text)
    private String bindingHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.privilege_share
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Integer)
    private Byte privilegeShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.cost
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Double)
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.suggested_price
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Double)
    private BigDecimal suggestedPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.apply_way
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    @Field(type = FieldType.Integer)
    private Byte applyWay;

    @Field(type = FieldType.Date)
    private Date createdTime;


    @Field(type = FieldType.text)
    private String description;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCouponInfoCode() {
        return couponInfoCode;
    }

    public void setCouponInfoCode(String couponInfoCode) {
        this.couponInfoCode = couponInfoCode;
    }

    public String getCouponInfoName() {
        return couponInfoName;
    }

    public void setCouponInfoName(String couponInfoName) {
        this.couponInfoName = couponInfoName;
    }

    public Byte getCouponCategoryId() {
        return couponCategoryId;
    }

    public void setCouponCategoryId(Byte couponCategoryId) {
        this.couponCategoryId = couponCategoryId;
    }

    public Byte getIsAvailable() {
        return isAvailable;
    }

    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }

    public String getBusinessName() {
        return businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public Long getShopId() {
        return shopId;
    }

    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    public Long getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    public Byte getFacture() {
        return facture;
    }

    public void setFacture(Byte facture) {
        this.facture = facture;
    }

    public Long getSubstituteId() {
        return substituteId;
    }

    public void setSubstituteId(Long substituteId) {
        this.substituteId = substituteId;
    }

    public String getSubstituteName() {
        return substituteName;
    }

    public void setSubstituteName(String substituteName) {
        this.substituteName = substituteName;
    }

    public Long getSubAgentId() {
        return subAgentId;
    }

    public void setSubAgentId(Long subAgentId) {
        this.subAgentId = subAgentId;
    }

    public Date getValidTime() {
        return validTime;
    }

    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    public Date getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    public Integer getValidDays() {
        return validDays;
    }

    public void setValidDays(Integer validDays) {
        this.validDays = validDays;
    }

    public BigDecimal getDenomination() {
        return denomination;
    }

    public void setDenomination(BigDecimal denomination) {
        this.denomination = denomination;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getDetailPic() {
        return detailPic;
    }

    public void setDetailPic(String detailPic) {
        this.detailPic = detailPic;
    }

    public Byte getApplyAllShop() {
        return applyAllShop;
    }

    public void setApplyAllShop(Byte applyAllShop) {
        this.applyAllShop = applyAllShop;
    }

    public Byte getIsAnytime() {
        return isAnytime;
    }

    public void setIsAnytime(Byte isAnytime) {
        this.isAnytime = isAnytime;
    }

    public String getBindingHours() {
        return bindingHours;
    }

    public void setBindingHours(String bindingHours) {
        this.bindingHours = bindingHours;
    }

    public Byte getPrivilegeShare() {
        return privilegeShare;
    }

    public void setPrivilegeShare(Byte privilegeShare) {
        this.privilegeShare = privilegeShare;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public BigDecimal getSuggestedPrice() {
        return suggestedPrice;
    }

    public void setSuggestedPrice(BigDecimal suggestedPrice) {
        this.suggestedPrice = suggestedPrice;
    }

    public Byte getApplyWay() {
        return applyWay;
    }

    public void setApplyWay(Byte applyWay) {
        this.applyWay = applyWay;
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "CaseInfoES{" +
                "id='" + id + '\'' +
                ", couponInfoCode='" + couponInfoCode + '\'' +
                ", couponInfoName='" + couponInfoName + '\'' +
                ", couponCategoryId=" + couponCategoryId +
                ", isAvailable=" + isAvailable +
                ", businessName='" + businessName + '\'' +
                ", shopId=" + shopId +
                ", merchantId=" + merchantId +
                ", facture=" + facture +
                ", substituteId=" + substituteId +
                ", substituteName='" + substituteName + '\'' +
                ", subAgentId=" + subAgentId +
                ", validTime=" + validTime +
                ", expireTime=" + expireTime +
                ", validDays=" + validDays +
                ", denomination=" + denomination +
                ", introduction='" + introduction + '\'' +
                ", detailPic='" + detailPic + '\'' +
                ", applyAllShop=" + applyAllShop +
                ", isAnytime=" + isAnytime +
                ", bindingHours='" + bindingHours + '\'' +
                ", privilegeShare=" + privilegeShare +
                ", cost=" + cost +
                ", suggestedPrice=" + suggestedPrice +
                ", applyWay=" + applyWay +
                ", createdTime=" + createdTime +
                ", description='" + description + '\'' +
                '}';
    }
}
