package me.gacl.domain;

import java.io.Serializable;
import java.util.Date;

public class CUser implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.id
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.user_name
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.password
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.type
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.scert
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private String scert;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.last_login_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.create_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.update_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.phone
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_user.deleted
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	private Integer deleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.id
	 * @return  the value of c_user.id
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.id
	 * @param id  the value for c_user.id
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.user_name
	 * @return  the value of c_user.user_name
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.user_name
	 * @param userName  the value for c_user.user_name
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.password
	 * @return  the value of c_user.password
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.password
	 * @param password  the value for c_user.password
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.type
	 * @return  the value of c_user.type
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.type
	 * @param type  the value for c_user.type
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.scert
	 * @return  the value of c_user.scert
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public String getScert() {
		return scert;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.scert
	 * @param scert  the value for c_user.scert
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setScert(String scert) {
		this.scert = scert;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.last_login_time
	 * @return  the value of c_user.last_login_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.last_login_time
	 * @param lastLoginTime  the value for c_user.last_login_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.create_time
	 * @return  the value of c_user.create_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.create_time
	 * @param createTime  the value for c_user.create_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.update_time
	 * @return  the value of c_user.update_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.update_time
	 * @param updateTime  the value for c_user.update_time
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.phone
	 * @return  the value of c_user.phone
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.phone
	 * @param phone  the value for c_user.phone
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_user.deleted
	 * @return  the value of c_user.deleted
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public Integer getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_user.deleted
	 * @param deleted  the value for c_user.deleted
	 * @mbggenerated  Sun Jul 31 16:08:34 CST 2016
	 */
	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}
}