package me.gacl.domain;

import java.io.Serializable;
import java.util.Date;

public class Dessy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dessy.id
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dessy.user_id
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dessy.content
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dessy.create_time
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dessy.update_time
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dessy
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dessy.id
     *
     * @return the value of dessy.id
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dessy.id
     *
     * @param id the value for dessy.id
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dessy.user_id
     *
     * @return the value of dessy.user_id
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dessy.user_id
     *
     * @param userId the value for dessy.user_id
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dessy.content
     *
     * @return the value of dessy.content
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dessy.content
     *
     * @param content the value for dessy.content
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dessy.create_time
     *
     * @return the value of dessy.create_time
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dessy.create_time
     *
     * @param createTime the value for dessy.create_time
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dessy.update_time
     *
     * @return the value of dessy.update_time
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dessy.update_time
     *
     * @param updateTime the value for dessy.update_time
     *
     * @mbggenerated Tue Oct 24 21:19:30 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}