package me.gacl.domain;

import java.io.Serializable;
import java.util.Date;

public class Disscuss implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscuss.id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscuss.user_id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscuss.parent_id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscuss.content
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscuss.create_time
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscuss.update_time
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscuss.type
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table disscuss
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscuss.id
     *
     * @return the value of disscuss.id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscuss.id
     *
     * @param id the value for disscuss.id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscuss.user_id
     *
     * @return the value of disscuss.user_id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscuss.user_id
     *
     * @param userId the value for disscuss.user_id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscuss.parent_id
     *
     * @return the value of disscuss.parent_id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscuss.parent_id
     *
     * @param parentId the value for disscuss.parent_id
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscuss.content
     *
     * @return the value of disscuss.content
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscuss.content
     *
     * @param content the value for disscuss.content
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscuss.create_time
     *
     * @return the value of disscuss.create_time
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscuss.create_time
     *
     * @param createTime the value for disscuss.create_time
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscuss.update_time
     *
     * @return the value of disscuss.update_time
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscuss.update_time
     *
     * @param updateTime the value for disscuss.update_time
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscuss.type
     *
     * @return the value of disscuss.type
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscuss.type
     *
     * @param type the value for disscuss.type
     *
     * @mbggenerated Tue Aug 30 17:49:00 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }
}