package me.gacl.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ECouponInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public ECouponInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeIsNull() {
            addCriterion("coupon_info_code is null");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeIsNotNull() {
            addCriterion("coupon_info_code is not null");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeEqualTo(String value) {
            addCriterion("coupon_info_code =", value, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeNotEqualTo(String value) {
            addCriterion("coupon_info_code <>", value, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeGreaterThan(String value) {
            addCriterion("coupon_info_code >", value, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_info_code >=", value, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeLessThan(String value) {
            addCriterion("coupon_info_code <", value, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeLessThanOrEqualTo(String value) {
            addCriterion("coupon_info_code <=", value, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeLike(String value) {
            addCriterion("coupon_info_code like", value, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeNotLike(String value) {
            addCriterion("coupon_info_code not like", value, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeIn(List<String> values) {
            addCriterion("coupon_info_code in", values, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeNotIn(List<String> values) {
            addCriterion("coupon_info_code not in", values, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeBetween(String value1, String value2) {
            addCriterion("coupon_info_code between", value1, value2, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoCodeNotBetween(String value1, String value2) {
            addCriterion("coupon_info_code not between", value1, value2, "couponInfoCode");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameIsNull() {
            addCriterion("coupon_info_name is null");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameIsNotNull() {
            addCriterion("coupon_info_name is not null");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameEqualTo(String value) {
            addCriterion("coupon_info_name =", value, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameNotEqualTo(String value) {
            addCriterion("coupon_info_name <>", value, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameGreaterThan(String value) {
            addCriterion("coupon_info_name >", value, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_info_name >=", value, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameLessThan(String value) {
            addCriterion("coupon_info_name <", value, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameLessThanOrEqualTo(String value) {
            addCriterion("coupon_info_name <=", value, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameLike(String value) {
            addCriterion("coupon_info_name like", value, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameNotLike(String value) {
            addCriterion("coupon_info_name not like", value, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameIn(List<String> values) {
            addCriterion("coupon_info_name in", values, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameNotIn(List<String> values) {
            addCriterion("coupon_info_name not in", values, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameBetween(String value1, String value2) {
            addCriterion("coupon_info_name between", value1, value2, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponInfoNameNotBetween(String value1, String value2) {
            addCriterion("coupon_info_name not between", value1, value2, "couponInfoName");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdIsNull() {
            addCriterion("coupon_category_id is null");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdIsNotNull() {
            addCriterion("coupon_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdEqualTo(Byte value) {
            addCriterion("coupon_category_id =", value, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdNotEqualTo(Byte value) {
            addCriterion("coupon_category_id <>", value, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdGreaterThan(Byte value) {
            addCriterion("coupon_category_id >", value, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdGreaterThanOrEqualTo(Byte value) {
            addCriterion("coupon_category_id >=", value, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdLessThan(Byte value) {
            addCriterion("coupon_category_id <", value, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdLessThanOrEqualTo(Byte value) {
            addCriterion("coupon_category_id <=", value, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdIn(List<Byte> values) {
            addCriterion("coupon_category_id in", values, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdNotIn(List<Byte> values) {
            addCriterion("coupon_category_id not in", values, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdBetween(Byte value1, Byte value2) {
            addCriterion("coupon_category_id between", value1, value2, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andCouponCategoryIdNotBetween(Byte value1, Byte value2) {
            addCriterion("coupon_category_id not between", value1, value2, "couponCategoryId");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIsNull() {
            addCriterion("is_available is null");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIsNotNull() {
            addCriterion("is_available is not null");
            return (Criteria) this;
        }

        public Criteria andIsAvailableEqualTo(Byte value) {
            addCriterion("is_available =", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotEqualTo(Byte value) {
            addCriterion("is_available <>", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableGreaterThan(Byte value) {
            addCriterion("is_available >", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_available >=", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableLessThan(Byte value) {
            addCriterion("is_available <", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableLessThanOrEqualTo(Byte value) {
            addCriterion("is_available <=", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIn(List<Byte> values) {
            addCriterion("is_available in", values, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotIn(List<Byte> values) {
            addCriterion("is_available not in", values, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableBetween(Byte value1, Byte value2) {
            addCriterion("is_available between", value1, value2, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotBetween(Byte value1, Byte value2) {
            addCriterion("is_available not between", value1, value2, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNull() {
            addCriterion("business_name is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNotNull() {
            addCriterion("business_name is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameEqualTo(String value) {
            addCriterion("business_name =", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotEqualTo(String value) {
            addCriterion("business_name <>", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThan(String value) {
            addCriterion("business_name >", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThanOrEqualTo(String value) {
            addCriterion("business_name >=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThan(String value) {
            addCriterion("business_name <", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThanOrEqualTo(String value) {
            addCriterion("business_name <=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLike(String value) {
            addCriterion("business_name like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotLike(String value) {
            addCriterion("business_name not like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIn(List<String> values) {
            addCriterion("business_name in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotIn(List<String> values) {
            addCriterion("business_name not in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameBetween(String value1, String value2) {
            addCriterion("business_name between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotBetween(String value1, String value2) {
            addCriterion("business_name not between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Long value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Long value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Long value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Long value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Long value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Long> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Long> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Long value1, Long value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Long value1, Long value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("merchant_id is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("merchant_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(Long value) {
            addCriterion("merchant_id =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(Long value) {
            addCriterion("merchant_id <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(Long value) {
            addCriterion("merchant_id >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("merchant_id >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(Long value) {
            addCriterion("merchant_id <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(Long value) {
            addCriterion("merchant_id <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<Long> values) {
            addCriterion("merchant_id in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<Long> values) {
            addCriterion("merchant_id not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(Long value1, Long value2) {
            addCriterion("merchant_id between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(Long value1, Long value2) {
            addCriterion("merchant_id not between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(Byte value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(Byte value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(Byte value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(Byte value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(Byte value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(Byte value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<Byte> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<Byte> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(Byte value1, Byte value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(Byte value1, Byte value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andFactureIsNull() {
            addCriterion("facture is null");
            return (Criteria) this;
        }

        public Criteria andFactureIsNotNull() {
            addCriterion("facture is not null");
            return (Criteria) this;
        }

        public Criteria andFactureEqualTo(Byte value) {
            addCriterion("facture =", value, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureNotEqualTo(Byte value) {
            addCriterion("facture <>", value, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureGreaterThan(Byte value) {
            addCriterion("facture >", value, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureGreaterThanOrEqualTo(Byte value) {
            addCriterion("facture >=", value, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureLessThan(Byte value) {
            addCriterion("facture <", value, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureLessThanOrEqualTo(Byte value) {
            addCriterion("facture <=", value, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureIn(List<Byte> values) {
            addCriterion("facture in", values, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureNotIn(List<Byte> values) {
            addCriterion("facture not in", values, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureBetween(Byte value1, Byte value2) {
            addCriterion("facture between", value1, value2, "facture");
            return (Criteria) this;
        }

        public Criteria andFactureNotBetween(Byte value1, Byte value2) {
            addCriterion("facture not between", value1, value2, "facture");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdIsNull() {
            addCriterion("substitute_id is null");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdIsNotNull() {
            addCriterion("substitute_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdEqualTo(Long value) {
            addCriterion("substitute_id =", value, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdNotEqualTo(Long value) {
            addCriterion("substitute_id <>", value, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdGreaterThan(Long value) {
            addCriterion("substitute_id >", value, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdGreaterThanOrEqualTo(Long value) {
            addCriterion("substitute_id >=", value, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdLessThan(Long value) {
            addCriterion("substitute_id <", value, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdLessThanOrEqualTo(Long value) {
            addCriterion("substitute_id <=", value, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdIn(List<Long> values) {
            addCriterion("substitute_id in", values, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdNotIn(List<Long> values) {
            addCriterion("substitute_id not in", values, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdBetween(Long value1, Long value2) {
            addCriterion("substitute_id between", value1, value2, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteIdNotBetween(Long value1, Long value2) {
            addCriterion("substitute_id not between", value1, value2, "substituteId");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameIsNull() {
            addCriterion("substitute_name is null");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameIsNotNull() {
            addCriterion("substitute_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameEqualTo(String value) {
            addCriterion("substitute_name =", value, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameNotEqualTo(String value) {
            addCriterion("substitute_name <>", value, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameGreaterThan(String value) {
            addCriterion("substitute_name >", value, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameGreaterThanOrEqualTo(String value) {
            addCriterion("substitute_name >=", value, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameLessThan(String value) {
            addCriterion("substitute_name <", value, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameLessThanOrEqualTo(String value) {
            addCriterion("substitute_name <=", value, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameLike(String value) {
            addCriterion("substitute_name like", value, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameNotLike(String value) {
            addCriterion("substitute_name not like", value, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameIn(List<String> values) {
            addCriterion("substitute_name in", values, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameNotIn(List<String> values) {
            addCriterion("substitute_name not in", values, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameBetween(String value1, String value2) {
            addCriterion("substitute_name between", value1, value2, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubstituteNameNotBetween(String value1, String value2) {
            addCriterion("substitute_name not between", value1, value2, "substituteName");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdIsNull() {
            addCriterion("sub_agent_id is null");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdIsNotNull() {
            addCriterion("sub_agent_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdEqualTo(Long value) {
            addCriterion("sub_agent_id =", value, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdNotEqualTo(Long value) {
            addCriterion("sub_agent_id <>", value, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdGreaterThan(Long value) {
            addCriterion("sub_agent_id >", value, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sub_agent_id >=", value, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdLessThan(Long value) {
            addCriterion("sub_agent_id <", value, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdLessThanOrEqualTo(Long value) {
            addCriterion("sub_agent_id <=", value, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdIn(List<Long> values) {
            addCriterion("sub_agent_id in", values, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdNotIn(List<Long> values) {
            addCriterion("sub_agent_id not in", values, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdBetween(Long value1, Long value2) {
            addCriterion("sub_agent_id between", value1, value2, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andSubAgentIdNotBetween(Long value1, Long value2) {
            addCriterion("sub_agent_id not between", value1, value2, "subAgentId");
            return (Criteria) this;
        }

        public Criteria andValidTimeIsNull() {
            addCriterion("valid_time is null");
            return (Criteria) this;
        }

        public Criteria andValidTimeIsNotNull() {
            addCriterion("valid_time is not null");
            return (Criteria) this;
        }

        public Criteria andValidTimeEqualTo(Date value) {
            addCriterion("valid_time =", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeNotEqualTo(Date value) {
            addCriterion("valid_time <>", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeGreaterThan(Date value) {
            addCriterion("valid_time >", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("valid_time >=", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeLessThan(Date value) {
            addCriterion("valid_time <", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeLessThanOrEqualTo(Date value) {
            addCriterion("valid_time <=", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeIn(List<Date> values) {
            addCriterion("valid_time in", values, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeNotIn(List<Date> values) {
            addCriterion("valid_time not in", values, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeBetween(Date value1, Date value2) {
            addCriterion("valid_time between", value1, value2, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeNotBetween(Date value1, Date value2) {
            addCriterion("valid_time not between", value1, value2, "validTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIsNull() {
            addCriterion("expire_time is null");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIsNotNull() {
            addCriterion("expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andExpireTimeEqualTo(Date value) {
            addCriterion("expire_time =", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotEqualTo(Date value) {
            addCriterion("expire_time <>", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeGreaterThan(Date value) {
            addCriterion("expire_time >", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("expire_time >=", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeLessThan(Date value) {
            addCriterion("expire_time <", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("expire_time <=", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIn(List<Date> values) {
            addCriterion("expire_time in", values, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotIn(List<Date> values) {
            addCriterion("expire_time not in", values, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeBetween(Date value1, Date value2) {
            addCriterion("expire_time between", value1, value2, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("expire_time not between", value1, value2, "expireTime");
            return (Criteria) this;
        }

        public Criteria andValidDaysIsNull() {
            addCriterion("valid_days is null");
            return (Criteria) this;
        }

        public Criteria andValidDaysIsNotNull() {
            addCriterion("valid_days is not null");
            return (Criteria) this;
        }

        public Criteria andValidDaysEqualTo(Integer value) {
            addCriterion("valid_days =", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysNotEqualTo(Integer value) {
            addCriterion("valid_days <>", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysGreaterThan(Integer value) {
            addCriterion("valid_days >", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("valid_days >=", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysLessThan(Integer value) {
            addCriterion("valid_days <", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysLessThanOrEqualTo(Integer value) {
            addCriterion("valid_days <=", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysIn(List<Integer> values) {
            addCriterion("valid_days in", values, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysNotIn(List<Integer> values) {
            addCriterion("valid_days not in", values, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysBetween(Integer value1, Integer value2) {
            addCriterion("valid_days between", value1, value2, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("valid_days not between", value1, value2, "validDays");
            return (Criteria) this;
        }

        public Criteria andDenominationIsNull() {
            addCriterion("denomination is null");
            return (Criteria) this;
        }

        public Criteria andDenominationIsNotNull() {
            addCriterion("denomination is not null");
            return (Criteria) this;
        }

        public Criteria andDenominationEqualTo(BigDecimal value) {
            addCriterion("denomination =", value, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationNotEqualTo(BigDecimal value) {
            addCriterion("denomination <>", value, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationGreaterThan(BigDecimal value) {
            addCriterion("denomination >", value, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("denomination >=", value, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationLessThan(BigDecimal value) {
            addCriterion("denomination <", value, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("denomination <=", value, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationIn(List<BigDecimal> values) {
            addCriterion("denomination in", values, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationNotIn(List<BigDecimal> values) {
            addCriterion("denomination not in", values, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("denomination between", value1, value2, "denomination");
            return (Criteria) this;
        }

        public Criteria andDenominationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("denomination not between", value1, value2, "denomination");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("introduction is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("introduction is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("introduction =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("introduction <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("introduction >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("introduction >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("introduction <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("introduction <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("introduction like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("introduction not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("introduction in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("introduction not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("introduction between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("introduction not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andDetailPicIsNull() {
            addCriterion("detail_pic is null");
            return (Criteria) this;
        }

        public Criteria andDetailPicIsNotNull() {
            addCriterion("detail_pic is not null");
            return (Criteria) this;
        }

        public Criteria andDetailPicEqualTo(String value) {
            addCriterion("detail_pic =", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicNotEqualTo(String value) {
            addCriterion("detail_pic <>", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicGreaterThan(String value) {
            addCriterion("detail_pic >", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicGreaterThanOrEqualTo(String value) {
            addCriterion("detail_pic >=", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicLessThan(String value) {
            addCriterion("detail_pic <", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicLessThanOrEqualTo(String value) {
            addCriterion("detail_pic <=", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicLike(String value) {
            addCriterion("detail_pic like", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicNotLike(String value) {
            addCriterion("detail_pic not like", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicIn(List<String> values) {
            addCriterion("detail_pic in", values, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicNotIn(List<String> values) {
            addCriterion("detail_pic not in", values, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicBetween(String value1, String value2) {
            addCriterion("detail_pic between", value1, value2, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicNotBetween(String value1, String value2) {
            addCriterion("detail_pic not between", value1, value2, "detailPic");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopIsNull() {
            addCriterion("apply_all_shop is null");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopIsNotNull() {
            addCriterion("apply_all_shop is not null");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopEqualTo(Byte value) {
            addCriterion("apply_all_shop =", value, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopNotEqualTo(Byte value) {
            addCriterion("apply_all_shop <>", value, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopGreaterThan(Byte value) {
            addCriterion("apply_all_shop >", value, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopGreaterThanOrEqualTo(Byte value) {
            addCriterion("apply_all_shop >=", value, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopLessThan(Byte value) {
            addCriterion("apply_all_shop <", value, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopLessThanOrEqualTo(Byte value) {
            addCriterion("apply_all_shop <=", value, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopIn(List<Byte> values) {
            addCriterion("apply_all_shop in", values, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopNotIn(List<Byte> values) {
            addCriterion("apply_all_shop not in", values, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopBetween(Byte value1, Byte value2) {
            addCriterion("apply_all_shop between", value1, value2, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andApplyAllShopNotBetween(Byte value1, Byte value2) {
            addCriterion("apply_all_shop not between", value1, value2, "applyAllShop");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeIsNull() {
            addCriterion("is_anytime is null");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeIsNotNull() {
            addCriterion("is_anytime is not null");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeEqualTo(Byte value) {
            addCriterion("is_anytime =", value, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeNotEqualTo(Byte value) {
            addCriterion("is_anytime <>", value, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeGreaterThan(Byte value) {
            addCriterion("is_anytime >", value, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_anytime >=", value, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeLessThan(Byte value) {
            addCriterion("is_anytime <", value, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeLessThanOrEqualTo(Byte value) {
            addCriterion("is_anytime <=", value, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeIn(List<Byte> values) {
            addCriterion("is_anytime in", values, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeNotIn(List<Byte> values) {
            addCriterion("is_anytime not in", values, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeBetween(Byte value1, Byte value2) {
            addCriterion("is_anytime between", value1, value2, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andIsAnytimeNotBetween(Byte value1, Byte value2) {
            addCriterion("is_anytime not between", value1, value2, "isAnytime");
            return (Criteria) this;
        }

        public Criteria andBindingHoursIsNull() {
            addCriterion("binding_hours is null");
            return (Criteria) this;
        }

        public Criteria andBindingHoursIsNotNull() {
            addCriterion("binding_hours is not null");
            return (Criteria) this;
        }

        public Criteria andBindingHoursEqualTo(String value) {
            addCriterion("binding_hours =", value, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursNotEqualTo(String value) {
            addCriterion("binding_hours <>", value, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursGreaterThan(String value) {
            addCriterion("binding_hours >", value, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursGreaterThanOrEqualTo(String value) {
            addCriterion("binding_hours >=", value, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursLessThan(String value) {
            addCriterion("binding_hours <", value, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursLessThanOrEqualTo(String value) {
            addCriterion("binding_hours <=", value, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursLike(String value) {
            addCriterion("binding_hours like", value, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursNotLike(String value) {
            addCriterion("binding_hours not like", value, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursIn(List<String> values) {
            addCriterion("binding_hours in", values, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursNotIn(List<String> values) {
            addCriterion("binding_hours not in", values, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursBetween(String value1, String value2) {
            addCriterion("binding_hours between", value1, value2, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andBindingHoursNotBetween(String value1, String value2) {
            addCriterion("binding_hours not between", value1, value2, "bindingHours");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareIsNull() {
            addCriterion("privilege_share is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareIsNotNull() {
            addCriterion("privilege_share is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareEqualTo(Byte value) {
            addCriterion("privilege_share =", value, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareNotEqualTo(Byte value) {
            addCriterion("privilege_share <>", value, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareGreaterThan(Byte value) {
            addCriterion("privilege_share >", value, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareGreaterThanOrEqualTo(Byte value) {
            addCriterion("privilege_share >=", value, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareLessThan(Byte value) {
            addCriterion("privilege_share <", value, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareLessThanOrEqualTo(Byte value) {
            addCriterion("privilege_share <=", value, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareIn(List<Byte> values) {
            addCriterion("privilege_share in", values, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareNotIn(List<Byte> values) {
            addCriterion("privilege_share not in", values, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareBetween(Byte value1, Byte value2) {
            addCriterion("privilege_share between", value1, value2, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andPrivilegeShareNotBetween(Byte value1, Byte value2) {
            addCriterion("privilege_share not between", value1, value2, "privilegeShare");
            return (Criteria) this;
        }

        public Criteria andCostIsNull() {
            addCriterion("cost is null");
            return (Criteria) this;
        }

        public Criteria andCostIsNotNull() {
            addCriterion("cost is not null");
            return (Criteria) this;
        }

        public Criteria andCostEqualTo(BigDecimal value) {
            addCriterion("cost =", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotEqualTo(BigDecimal value) {
            addCriterion("cost <>", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostGreaterThan(BigDecimal value) {
            addCriterion("cost >", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cost >=", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostLessThan(BigDecimal value) {
            addCriterion("cost <", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cost <=", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostIn(List<BigDecimal> values) {
            addCriterion("cost in", values, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotIn(List<BigDecimal> values) {
            addCriterion("cost not in", values, "cost");
            return (Criteria) this;
        }

        public Criteria andCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost between", value1, value2, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost not between", value1, value2, "cost");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceIsNull() {
            addCriterion("suggested_price is null");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceIsNotNull() {
            addCriterion("suggested_price is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceEqualTo(BigDecimal value) {
            addCriterion("suggested_price =", value, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceNotEqualTo(BigDecimal value) {
            addCriterion("suggested_price <>", value, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceGreaterThan(BigDecimal value) {
            addCriterion("suggested_price >", value, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("suggested_price >=", value, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceLessThan(BigDecimal value) {
            addCriterion("suggested_price <", value, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("suggested_price <=", value, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceIn(List<BigDecimal> values) {
            addCriterion("suggested_price in", values, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceNotIn(List<BigDecimal> values) {
            addCriterion("suggested_price not in", values, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("suggested_price between", value1, value2, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andSuggestedPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("suggested_price not between", value1, value2, "suggestedPrice");
            return (Criteria) this;
        }

        public Criteria andApplyWayIsNull() {
            addCriterion("apply_way is null");
            return (Criteria) this;
        }

        public Criteria andApplyWayIsNotNull() {
            addCriterion("apply_way is not null");
            return (Criteria) this;
        }

        public Criteria andApplyWayEqualTo(Byte value) {
            addCriterion("apply_way =", value, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayNotEqualTo(Byte value) {
            addCriterion("apply_way <>", value, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayGreaterThan(Byte value) {
            addCriterion("apply_way >", value, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayGreaterThanOrEqualTo(Byte value) {
            addCriterion("apply_way >=", value, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayLessThan(Byte value) {
            addCriterion("apply_way <", value, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayLessThanOrEqualTo(Byte value) {
            addCriterion("apply_way <=", value, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayIn(List<Byte> values) {
            addCriterion("apply_way in", values, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayNotIn(List<Byte> values) {
            addCriterion("apply_way not in", values, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayBetween(Byte value1, Byte value2) {
            addCriterion("apply_way between", value1, value2, "applyWay");
            return (Criteria) this;
        }

        public Criteria andApplyWayNotBetween(Byte value1, Byte value2) {
            addCriterion("apply_way not between", value1, value2, "applyWay");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryIsNull() {
            addCriterion("total_inventory is null");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryIsNotNull() {
            addCriterion("total_inventory is not null");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryEqualTo(Integer value) {
            addCriterion("total_inventory =", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryNotEqualTo(Integer value) {
            addCriterion("total_inventory <>", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryGreaterThan(Integer value) {
            addCriterion("total_inventory >", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_inventory >=", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryLessThan(Integer value) {
            addCriterion("total_inventory <", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryLessThanOrEqualTo(Integer value) {
            addCriterion("total_inventory <=", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryIn(List<Integer> values) {
            addCriterion("total_inventory in", values, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryNotIn(List<Integer> values) {
            addCriterion("total_inventory not in", values, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryBetween(Integer value1, Integer value2) {
            addCriterion("total_inventory between", value1, value2, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryNotBetween(Integer value1, Integer value2) {
            addCriterion("total_inventory not between", value1, value2, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberIsNull() {
            addCriterion("receive_number is null");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberIsNotNull() {
            addCriterion("receive_number is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberEqualTo(Integer value) {
            addCriterion("receive_number =", value, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberNotEqualTo(Integer value) {
            addCriterion("receive_number <>", value, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberGreaterThan(Integer value) {
            addCriterion("receive_number >", value, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("receive_number >=", value, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberLessThan(Integer value) {
            addCriterion("receive_number <", value, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberLessThanOrEqualTo(Integer value) {
            addCriterion("receive_number <=", value, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberIn(List<Integer> values) {
            addCriterion("receive_number in", values, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberNotIn(List<Integer> values) {
            addCriterion("receive_number not in", values, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberBetween(Integer value1, Integer value2) {
            addCriterion("receive_number between", value1, value2, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andReceiveNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("receive_number not between", value1, value2, "receiveNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberIsNull() {
            addCriterion("freeze_number is null");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberIsNotNull() {
            addCriterion("freeze_number is not null");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberEqualTo(Integer value) {
            addCriterion("freeze_number =", value, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberNotEqualTo(Integer value) {
            addCriterion("freeze_number <>", value, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberGreaterThan(Integer value) {
            addCriterion("freeze_number >", value, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("freeze_number >=", value, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberLessThan(Integer value) {
            addCriterion("freeze_number <", value, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberLessThanOrEqualTo(Integer value) {
            addCriterion("freeze_number <=", value, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberIn(List<Integer> values) {
            addCriterion("freeze_number in", values, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberNotIn(List<Integer> values) {
            addCriterion("freeze_number not in", values, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberBetween(Integer value1, Integer value2) {
            addCriterion("freeze_number between", value1, value2, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andFreezeNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("freeze_number not between", value1, value2, "freezeNumber");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andListPicIsNull() {
            addCriterion("list_pic is null");
            return (Criteria) this;
        }

        public Criteria andListPicIsNotNull() {
            addCriterion("list_pic is not null");
            return (Criteria) this;
        }

        public Criteria andListPicEqualTo(String value) {
            addCriterion("list_pic =", value, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicNotEqualTo(String value) {
            addCriterion("list_pic <>", value, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicGreaterThan(String value) {
            addCriterion("list_pic >", value, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicGreaterThanOrEqualTo(String value) {
            addCriterion("list_pic >=", value, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicLessThan(String value) {
            addCriterion("list_pic <", value, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicLessThanOrEqualTo(String value) {
            addCriterion("list_pic <=", value, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicLike(String value) {
            addCriterion("list_pic like", value, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicNotLike(String value) {
            addCriterion("list_pic not like", value, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicIn(List<String> values) {
            addCriterion("list_pic in", values, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicNotIn(List<String> values) {
            addCriterion("list_pic not in", values, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicBetween(String value1, String value2) {
            addCriterion("list_pic between", value1, value2, "listPic");
            return (Criteria) this;
        }

        public Criteria andListPicNotBetween(String value1, String value2) {
            addCriterion("list_pic not between", value1, value2, "listPic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_coupon_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 24 14:56:44 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}