package me.gacl.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ECoupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.x_card_user_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String xCardUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.coupon_discount_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String couponDiscountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.coupon_verify_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String couponVerifyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.mobile_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String mobileNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.coupon_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String couponOrderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.order_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.coupon_info_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String couponInfoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.coupon_info_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String couponInfoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.coupon_info_channel_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long couponInfoChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.coupon_info_channel_detail_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long couponInfoChannelDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.wemall_sale_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long wemallSaleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.wemall_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long wemallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.coupon_category_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte couponCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.general
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte general;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.actual_price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private BigDecimal actualPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.server_fee
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private BigDecimal serverFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.exchange_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte exchangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.denomination
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private BigDecimal denomination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.exchange_price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long exchangePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.shop_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.shop_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.operator_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.operator_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.result
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.verify_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Date verifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.refund_apply_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Date refundApplyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.refund_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Date refundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.refund_reason
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String refundReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.refund_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String refundOrderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.enable_refund
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte enableRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.refund_url
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String refundUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.get_channel
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte getChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.get_channel_detail
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Integer getChannelDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.valid_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Date validTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.expire_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.created_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.updated_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.payment_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.payment_type_str
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String paymentTypeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.accept_business_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long acceptBusinessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.accept_business_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String acceptBusinessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.accept_business_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String acceptBusinessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.status
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.comment
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.order_shop_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long orderShopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.order_merchant_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Long orderMerchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.client_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private Byte clientCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon.lock_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private String lockOrderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_coupon
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.id
     *
     * @return the value of e_coupon.id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.id
     *
     * @param id the value for e_coupon.id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.x_card_user_id
     *
     * @return the value of e_coupon.x_card_user_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getxCardUserId() {
        return xCardUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.x_card_user_id
     *
     * @param xCardUserId the value for e_coupon.x_card_user_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setxCardUserId(String xCardUserId) {
        this.xCardUserId = xCardUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.coupon_discount_code
     *
     * @return the value of e_coupon.coupon_discount_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getCouponDiscountCode() {
        return couponDiscountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.coupon_discount_code
     *
     * @param couponDiscountCode the value for e_coupon.coupon_discount_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCouponDiscountCode(String couponDiscountCode) {
        this.couponDiscountCode = couponDiscountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.coupon_verify_code
     *
     * @return the value of e_coupon.coupon_verify_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getCouponVerifyCode() {
        return couponVerifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.coupon_verify_code
     *
     * @param couponVerifyCode the value for e_coupon.coupon_verify_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCouponVerifyCode(String couponVerifyCode) {
        this.couponVerifyCode = couponVerifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.mobile_number
     *
     * @return the value of e_coupon.mobile_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.mobile_number
     *
     * @param mobileNumber the value for e_coupon.mobile_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.coupon_order_number
     *
     * @return the value of e_coupon.coupon_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getCouponOrderNumber() {
        return couponOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.coupon_order_number
     *
     * @param couponOrderNumber the value for e_coupon.coupon_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCouponOrderNumber(String couponOrderNumber) {
        this.couponOrderNumber = couponOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.order_type
     *
     * @return the value of e_coupon.order_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.order_type
     *
     * @param orderType the value for e_coupon.order_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setOrderType(Byte orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.coupon_info_code
     *
     * @return the value of e_coupon.coupon_info_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getCouponInfoCode() {
        return couponInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.coupon_info_code
     *
     * @param couponInfoCode the value for e_coupon.coupon_info_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCouponInfoCode(String couponInfoCode) {
        this.couponInfoCode = couponInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.coupon_info_name
     *
     * @return the value of e_coupon.coupon_info_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getCouponInfoName() {
        return couponInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.coupon_info_name
     *
     * @param couponInfoName the value for e_coupon.coupon_info_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCouponInfoName(String couponInfoName) {
        this.couponInfoName = couponInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.coupon_info_channel_id
     *
     * @return the value of e_coupon.coupon_info_channel_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getCouponInfoChannelId() {
        return couponInfoChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.coupon_info_channel_id
     *
     * @param couponInfoChannelId the value for e_coupon.coupon_info_channel_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCouponInfoChannelId(Long couponInfoChannelId) {
        this.couponInfoChannelId = couponInfoChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.coupon_info_channel_detail_id
     *
     * @return the value of e_coupon.coupon_info_channel_detail_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getCouponInfoChannelDetailId() {
        return couponInfoChannelDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.coupon_info_channel_detail_id
     *
     * @param couponInfoChannelDetailId the value for e_coupon.coupon_info_channel_detail_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCouponInfoChannelDetailId(Long couponInfoChannelDetailId) {
        this.couponInfoChannelDetailId = couponInfoChannelDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.wemall_sale_id
     *
     * @return the value of e_coupon.wemall_sale_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getWemallSaleId() {
        return wemallSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.wemall_sale_id
     *
     * @param wemallSaleId the value for e_coupon.wemall_sale_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setWemallSaleId(Long wemallSaleId) {
        this.wemallSaleId = wemallSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.wemall_id
     *
     * @return the value of e_coupon.wemall_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getWemallId() {
        return wemallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.wemall_id
     *
     * @param wemallId the value for e_coupon.wemall_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setWemallId(Long wemallId) {
        this.wemallId = wemallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.coupon_category_id
     *
     * @return the value of e_coupon.coupon_category_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getCouponCategoryId() {
        return couponCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.coupon_category_id
     *
     * @param couponCategoryId the value for e_coupon.coupon_category_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCouponCategoryId(Byte couponCategoryId) {
        this.couponCategoryId = couponCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.general
     *
     * @return the value of e_coupon.general
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getGeneral() {
        return general;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.general
     *
     * @param general the value for e_coupon.general
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setGeneral(Byte general) {
        this.general = general;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.actual_price
     *
     * @return the value of e_coupon.actual_price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public BigDecimal getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.actual_price
     *
     * @param actualPrice the value for e_coupon.actual_price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.server_fee
     *
     * @return the value of e_coupon.server_fee
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public BigDecimal getServerFee() {
        return serverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.server_fee
     *
     * @param serverFee the value for e_coupon.server_fee
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setServerFee(BigDecimal serverFee) {
        this.serverFee = serverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.price
     *
     * @return the value of e_coupon.price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.price
     *
     * @param price the value for e_coupon.price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.exchange_type
     *
     * @return the value of e_coupon.exchange_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getExchangeType() {
        return exchangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.exchange_type
     *
     * @param exchangeType the value for e_coupon.exchange_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setExchangeType(Byte exchangeType) {
        this.exchangeType = exchangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.denomination
     *
     * @return the value of e_coupon.denomination
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public BigDecimal getDenomination() {
        return denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.denomination
     *
     * @param denomination the value for e_coupon.denomination
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setDenomination(BigDecimal denomination) {
        this.denomination = denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.exchange_price
     *
     * @return the value of e_coupon.exchange_price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getExchangePrice() {
        return exchangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.exchange_price
     *
     * @param exchangePrice the value for e_coupon.exchange_price
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setExchangePrice(Long exchangePrice) {
        this.exchangePrice = exchangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.shop_id
     *
     * @return the value of e_coupon.shop_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.shop_id
     *
     * @param shopId the value for e_coupon.shop_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.shop_name
     *
     * @return the value of e_coupon.shop_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.shop_name
     *
     * @param shopName the value for e_coupon.shop_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.operator_name
     *
     * @return the value of e_coupon.operator_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.operator_name
     *
     * @param operatorName the value for e_coupon.operator_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.operator_id
     *
     * @return the value of e_coupon.operator_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.operator_id
     *
     * @param operatorId the value for e_coupon.operator_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.result
     *
     * @return the value of e_coupon.result
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.result
     *
     * @param result the value for e_coupon.result
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setResult(Byte result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.verify_time
     *
     * @return the value of e_coupon.verify_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Date getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.verify_time
     *
     * @param verifyTime the value for e_coupon.verify_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setVerifyTime(Date verifyTime) {
        this.verifyTime = verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.refund_apply_time
     *
     * @return the value of e_coupon.refund_apply_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Date getRefundApplyTime() {
        return refundApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.refund_apply_time
     *
     * @param refundApplyTime the value for e_coupon.refund_apply_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setRefundApplyTime(Date refundApplyTime) {
        this.refundApplyTime = refundApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.refund_time
     *
     * @return the value of e_coupon.refund_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.refund_time
     *
     * @param refundTime the value for e_coupon.refund_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.refund_reason
     *
     * @return the value of e_coupon.refund_reason
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getRefundReason() {
        return refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.refund_reason
     *
     * @param refundReason the value for e_coupon.refund_reason
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setRefundReason(String refundReason) {
        this.refundReason = refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.refund_order_number
     *
     * @return the value of e_coupon.refund_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getRefundOrderNumber() {
        return refundOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.refund_order_number
     *
     * @param refundOrderNumber the value for e_coupon.refund_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setRefundOrderNumber(String refundOrderNumber) {
        this.refundOrderNumber = refundOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.enable_refund
     *
     * @return the value of e_coupon.enable_refund
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getEnableRefund() {
        return enableRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.enable_refund
     *
     * @param enableRefund the value for e_coupon.enable_refund
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setEnableRefund(Byte enableRefund) {
        this.enableRefund = enableRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.refund_url
     *
     * @return the value of e_coupon.refund_url
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getRefundUrl() {
        return refundUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.refund_url
     *
     * @param refundUrl the value for e_coupon.refund_url
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setRefundUrl(String refundUrl) {
        this.refundUrl = refundUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.get_channel
     *
     * @return the value of e_coupon.get_channel
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getGetChannel() {
        return getChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.get_channel
     *
     * @param getChannel the value for e_coupon.get_channel
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setGetChannel(Byte getChannel) {
        this.getChannel = getChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.get_channel_detail
     *
     * @return the value of e_coupon.get_channel_detail
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Integer getGetChannelDetail() {
        return getChannelDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.get_channel_detail
     *
     * @param getChannelDetail the value for e_coupon.get_channel_detail
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setGetChannelDetail(Integer getChannelDetail) {
        this.getChannelDetail = getChannelDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.valid_time
     *
     * @return the value of e_coupon.valid_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Date getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.valid_time
     *
     * @param validTime the value for e_coupon.valid_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.expire_time
     *
     * @return the value of e_coupon.expire_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.expire_time
     *
     * @param expireTime the value for e_coupon.expire_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.created_time
     *
     * @return the value of e_coupon.created_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.created_time
     *
     * @param createdTime the value for e_coupon.created_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.updated_time
     *
     * @return the value of e_coupon.updated_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.updated_time
     *
     * @param updatedTime the value for e_coupon.updated_time
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.payment_type
     *
     * @return the value of e_coupon.payment_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.payment_type
     *
     * @param paymentType the value for e_coupon.payment_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setPaymentType(Byte paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.payment_type_str
     *
     * @return the value of e_coupon.payment_type_str
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getPaymentTypeStr() {
        return paymentTypeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.payment_type_str
     *
     * @param paymentTypeStr the value for e_coupon.payment_type_str
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setPaymentTypeStr(String paymentTypeStr) {
        this.paymentTypeStr = paymentTypeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.accept_business_id
     *
     * @return the value of e_coupon.accept_business_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getAcceptBusinessId() {
        return acceptBusinessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.accept_business_id
     *
     * @param acceptBusinessId the value for e_coupon.accept_business_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setAcceptBusinessId(Long acceptBusinessId) {
        this.acceptBusinessId = acceptBusinessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.accept_business_type
     *
     * @return the value of e_coupon.accept_business_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getAcceptBusinessType() {
        return acceptBusinessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.accept_business_type
     *
     * @param acceptBusinessType the value for e_coupon.accept_business_type
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setAcceptBusinessType(String acceptBusinessType) {
        this.acceptBusinessType = acceptBusinessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.accept_business_name
     *
     * @return the value of e_coupon.accept_business_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getAcceptBusinessName() {
        return acceptBusinessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.accept_business_name
     *
     * @param acceptBusinessName the value for e_coupon.accept_business_name
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setAcceptBusinessName(String acceptBusinessName) {
        this.acceptBusinessName = acceptBusinessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.status
     *
     * @return the value of e_coupon.status
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.status
     *
     * @param status the value for e_coupon.status
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.comment
     *
     * @return the value of e_coupon.comment
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.comment
     *
     * @param comment the value for e_coupon.comment
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.order_shop_id
     *
     * @return the value of e_coupon.order_shop_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getOrderShopId() {
        return orderShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.order_shop_id
     *
     * @param orderShopId the value for e_coupon.order_shop_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setOrderShopId(Long orderShopId) {
        this.orderShopId = orderShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.order_merchant_id
     *
     * @return the value of e_coupon.order_merchant_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Long getOrderMerchantId() {
        return orderMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.order_merchant_id
     *
     * @param orderMerchantId the value for e_coupon.order_merchant_id
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setOrderMerchantId(Long orderMerchantId) {
        this.orderMerchantId = orderMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.client_code
     *
     * @return the value of e_coupon.client_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public Byte getClientCode() {
        return clientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.client_code
     *
     * @param clientCode the value for e_coupon.client_code
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setClientCode(Byte clientCode) {
        this.clientCode = clientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon.lock_order_number
     *
     * @return the value of e_coupon.lock_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public String getLockOrderNumber() {
        return lockOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon.lock_order_number
     *
     * @param lockOrderNumber the value for e_coupon.lock_order_number
     *
     * @mbggenerated Mon Dec 25 14:13:11 CST 2017
     */
    public void setLockOrderNumber(String lockOrderNumber) {
        this.lockOrderNumber = lockOrderNumber;
    }
}