package me.gacl.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ECouponInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.coupon_info_code
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String couponInfoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.coupon_info_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String couponInfoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.coupon_category_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte couponCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.is_available
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte isAvailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.business_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.shop_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.merchant_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.source
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.facture
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte facture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.substitute_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Long substituteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.substitute_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String substituteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.sub_agent_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Long subAgentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.valid_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Date validTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.expire_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.valid_days
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Integer validDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.denomination
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private BigDecimal denomination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.introduction
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.detail_pic
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String detailPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.apply_all_shop
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte applyAllShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.is_anytime
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte isAnytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.binding_hours
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String bindingHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.privilege_share
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte privilegeShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.cost
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.suggested_price
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private BigDecimal suggestedPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.apply_way
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte applyWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.total_inventory
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Integer totalInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.receive_number
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Integer receiveNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.freeze_number
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Integer freezeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.created_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.updated_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.status
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.comment
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.list_pic
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String listPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_coupon_info.description
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_coupon_info
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.id
     *
     * @return the value of e_coupon_info.id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.id
     *
     * @param id the value for e_coupon_info.id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.coupon_info_code
     *
     * @return the value of e_coupon_info.coupon_info_code
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getCouponInfoCode() {
        return couponInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.coupon_info_code
     *
     * @param couponInfoCode the value for e_coupon_info.coupon_info_code
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setCouponInfoCode(String couponInfoCode) {
        this.couponInfoCode = couponInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.coupon_info_name
     *
     * @return the value of e_coupon_info.coupon_info_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getCouponInfoName() {
        return couponInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.coupon_info_name
     *
     * @param couponInfoName the value for e_coupon_info.coupon_info_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setCouponInfoName(String couponInfoName) {
        this.couponInfoName = couponInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.coupon_category_id
     *
     * @return the value of e_coupon_info.coupon_category_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getCouponCategoryId() {
        return couponCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.coupon_category_id
     *
     * @param couponCategoryId the value for e_coupon_info.coupon_category_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setCouponCategoryId(Byte couponCategoryId) {
        this.couponCategoryId = couponCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.is_available
     *
     * @return the value of e_coupon_info.is_available
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.is_available
     *
     * @param isAvailable the value for e_coupon_info.is_available
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.business_name
     *
     * @return the value of e_coupon_info.business_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.business_name
     *
     * @param businessName the value for e_coupon_info.business_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.shop_id
     *
     * @return the value of e_coupon_info.shop_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.shop_id
     *
     * @param shopId the value for e_coupon_info.shop_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.merchant_id
     *
     * @return the value of e_coupon_info.merchant_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.merchant_id
     *
     * @param merchantId the value for e_coupon_info.merchant_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.source
     *
     * @return the value of e_coupon_info.source
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.source
     *
     * @param source the value for e_coupon_info.source
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.facture
     *
     * @return the value of e_coupon_info.facture
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getFacture() {
        return facture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.facture
     *
     * @param facture the value for e_coupon_info.facture
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setFacture(Byte facture) {
        this.facture = facture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.substitute_id
     *
     * @return the value of e_coupon_info.substitute_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Long getSubstituteId() {
        return substituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.substitute_id
     *
     * @param substituteId the value for e_coupon_info.substitute_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setSubstituteId(Long substituteId) {
        this.substituteId = substituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.substitute_name
     *
     * @return the value of e_coupon_info.substitute_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getSubstituteName() {
        return substituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.substitute_name
     *
     * @param substituteName the value for e_coupon_info.substitute_name
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setSubstituteName(String substituteName) {
        this.substituteName = substituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.sub_agent_id
     *
     * @return the value of e_coupon_info.sub_agent_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Long getSubAgentId() {
        return subAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.sub_agent_id
     *
     * @param subAgentId the value for e_coupon_info.sub_agent_id
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setSubAgentId(Long subAgentId) {
        this.subAgentId = subAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.valid_time
     *
     * @return the value of e_coupon_info.valid_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Date getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.valid_time
     *
     * @param validTime the value for e_coupon_info.valid_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.expire_time
     *
     * @return the value of e_coupon_info.expire_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.expire_time
     *
     * @param expireTime the value for e_coupon_info.expire_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.valid_days
     *
     * @return the value of e_coupon_info.valid_days
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Integer getValidDays() {
        return validDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.valid_days
     *
     * @param validDays the value for e_coupon_info.valid_days
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setValidDays(Integer validDays) {
        this.validDays = validDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.denomination
     *
     * @return the value of e_coupon_info.denomination
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public BigDecimal getDenomination() {
        return denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.denomination
     *
     * @param denomination the value for e_coupon_info.denomination
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setDenomination(BigDecimal denomination) {
        this.denomination = denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.introduction
     *
     * @return the value of e_coupon_info.introduction
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.introduction
     *
     * @param introduction the value for e_coupon_info.introduction
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.detail_pic
     *
     * @return the value of e_coupon_info.detail_pic
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getDetailPic() {
        return detailPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.detail_pic
     *
     * @param detailPic the value for e_coupon_info.detail_pic
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setDetailPic(String detailPic) {
        this.detailPic = detailPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.apply_all_shop
     *
     * @return the value of e_coupon_info.apply_all_shop
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getApplyAllShop() {
        return applyAllShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.apply_all_shop
     *
     * @param applyAllShop the value for e_coupon_info.apply_all_shop
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setApplyAllShop(Byte applyAllShop) {
        this.applyAllShop = applyAllShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.is_anytime
     *
     * @return the value of e_coupon_info.is_anytime
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getIsAnytime() {
        return isAnytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.is_anytime
     *
     * @param isAnytime the value for e_coupon_info.is_anytime
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setIsAnytime(Byte isAnytime) {
        this.isAnytime = isAnytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.binding_hours
     *
     * @return the value of e_coupon_info.binding_hours
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getBindingHours() {
        return bindingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.binding_hours
     *
     * @param bindingHours the value for e_coupon_info.binding_hours
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setBindingHours(String bindingHours) {
        this.bindingHours = bindingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.privilege_share
     *
     * @return the value of e_coupon_info.privilege_share
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getPrivilegeShare() {
        return privilegeShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.privilege_share
     *
     * @param privilegeShare the value for e_coupon_info.privilege_share
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setPrivilegeShare(Byte privilegeShare) {
        this.privilegeShare = privilegeShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.cost
     *
     * @return the value of e_coupon_info.cost
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.cost
     *
     * @param cost the value for e_coupon_info.cost
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.suggested_price
     *
     * @return the value of e_coupon_info.suggested_price
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public BigDecimal getSuggestedPrice() {
        return suggestedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.suggested_price
     *
     * @param suggestedPrice the value for e_coupon_info.suggested_price
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setSuggestedPrice(BigDecimal suggestedPrice) {
        this.suggestedPrice = suggestedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.apply_way
     *
     * @return the value of e_coupon_info.apply_way
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getApplyWay() {
        return applyWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.apply_way
     *
     * @param applyWay the value for e_coupon_info.apply_way
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setApplyWay(Byte applyWay) {
        this.applyWay = applyWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.total_inventory
     *
     * @return the value of e_coupon_info.total_inventory
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Integer getTotalInventory() {
        return totalInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.total_inventory
     *
     * @param totalInventory the value for e_coupon_info.total_inventory
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setTotalInventory(Integer totalInventory) {
        this.totalInventory = totalInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.receive_number
     *
     * @return the value of e_coupon_info.receive_number
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Integer getReceiveNumber() {
        return receiveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.receive_number
     *
     * @param receiveNumber the value for e_coupon_info.receive_number
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setReceiveNumber(Integer receiveNumber) {
        this.receiveNumber = receiveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.freeze_number
     *
     * @return the value of e_coupon_info.freeze_number
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Integer getFreezeNumber() {
        return freezeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.freeze_number
     *
     * @param freezeNumber the value for e_coupon_info.freeze_number
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setFreezeNumber(Integer freezeNumber) {
        this.freezeNumber = freezeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.created_time
     *
     * @return the value of e_coupon_info.created_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.created_time
     *
     * @param createdTime the value for e_coupon_info.created_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.updated_time
     *
     * @return the value of e_coupon_info.updated_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.updated_time
     *
     * @param updatedTime the value for e_coupon_info.updated_time
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.status
     *
     * @return the value of e_coupon_info.status
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.status
     *
     * @param status the value for e_coupon_info.status
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.comment
     *
     * @return the value of e_coupon_info.comment
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.comment
     *
     * @param comment the value for e_coupon_info.comment
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.list_pic
     *
     * @return the value of e_coupon_info.list_pic
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getListPic() {
        return listPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.list_pic
     *
     * @param listPic the value for e_coupon_info.list_pic
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setListPic(String listPic) {
        this.listPic = listPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_coupon_info.description
     *
     * @return the value of e_coupon_info.description
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_coupon_info.description
     *
     * @param description the value for e_coupon_info.description
     *
     * @mbggenerated Sun Dec 24 14:56:44 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}